flowchart TD
    start((Start))
    subgraph Try["Try block"]
        UserInput[/"Input Inches"/]
        -->
        ToInt["Converts Inches input to int"]
        -->
        CalculateFeet["calculate feet = inches // 12"]
        -->
        CalculateRemainder["remaining_inches = inches % 12"]
        -->
        PrintOut[\"Prints out the results"\]
    end
    start --> UserInput

    PrintOut --> Exit

    Try --> |Exception| PrintErr[\"Please enter a valid number"\]
    --> Exit["Exit"]
